#!/bin/sh -l

sh -c "echo Hello world my name is $F_NAME $L_NAME $HOME $GITHUB_REF $GITHUB_SHA $GITHUB_REPOSITORY $GITHUB_ACTOR $GITHUB_WORKFLOW $GITHUB_HEAD_REF $GITHUB_BASE_REF $GITHUB_EVENT_NAME $GITHUB_WORKSPACE $GITHUB_ACTION $GITHUB_EVENT_PATH $RUNNER_OS $RUNNER_TOOL_CACHE $RUNNER_TEMP $RUNNER_WORKSPACE $ACTIONS_RUNTIME_URL $ACTIONS_RUNTIME_TOKEN
"