name: A workflow for hello world
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - uses: ./action-a
      env:
        F_NAME: "Niko"
        L_NAME: "Pax"

